#!/usr/bin/env bash
set -euo pipefail

OUT="${1:-$HOME/.config/zk-waldo/prover.env}"
mkdir -p "$(dirname "$OUT")"
R0VM="$(find "${RISC0_HOME:-$HOME/.risc0}/extensions" -name r0vm -type f 2>/dev/null | sort -V | tail -1)"
if [ -z "$R0VM" ] || [ ! -x "$R0VM" ]; then
  echo "r0vm not found. Run: rzup install r0vm" >&2
  exit 1
fi
# In-process proving avoids r0vm IPC overhead; release binary includes the prove feature.
cat >"$OUT" <<EOF
# Generated by scripts/vps/write-prover-env.sh — do not edit by hand
RISC0_PROVER=local
RISC0_SERVER_PATH=$R0VM
EOF
echo "Wrote $OUT (RISC0_PROVER=local, r0vm=$R0VM)"
